# config/routes.yaml

app_api:
    resource: ../src/Presentation/Api/Controller
    type: attribute
    prefix: /api/

app_manager:
    resource: ../src/Presentation/Web/Controller/Manager
    type: attribute
    prefix: /manager

app_customer:
    resource: ../src/Presentation/Web/Controller/Customer
    type: attribute
    prefix: /customer

app_public:
    resource: ../src/Presentation/Web/Controller/NonAuth
    type: attribute
    prefix: /
